robot:
  limb/left:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2

    gains:
      left_s0: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_s0: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_e0: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_e1: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_w0: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_w1: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_w2: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}


  end_effector/left_gripper:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - l_gripper_r_finger_joint
      - l_gripper_l_finger_joint
    gains:
      l_gripper_r_finger_joint:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
      l_gripper_l_finger_joint:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
